name: Test 3
on: [push]
jobs:
  test1:
    name: Test 3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Setup Test 3
      run: python find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt
    - name: Run Test 3
      run: diff test_data/test3_expected.txt test_data/test3_output.txt
